### ISSUE TITLE
什么时候能更新下啊？

### ISSUE THREAD

**Issue by praming** [lqzhgood/bulma-docs-cn#1]
什么时候能更新下啊？现在是0.7.1了

**Comment by lqzhgood** [comment]
瞄了下~ HTML结构又大改了 :cry:
最近不得空哎~

**Comment by seekdoor** [comment]
同问啥时候可以再次更新一下文档.

**Comment by g-zhima** [comment]
现在0.7.2了，英文不好，对着中文文档看英文，有些地方确实该更新一下了😂

**Comment by lqzhgood** [comment]
这个作者一个版本页面就一次大改~ 都不重用的
HTML全变了  每次汉化要从0开始……
十分蛋疼 ~

**Comment by lqzhgood** [comment]
感谢 @vmlite https://v2ex.com/member/vmlite 翻译 v0.8
可以访问 https://bulma.comptechs.cn/ 查看
